# Generated by Django 5.1.3 on 2025-10-15 07:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shareCapital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_type', models.CharField(choices=[('Member', 'Member'), ('Account', 'Account'), ('Loan', 'Loan'), ('Payment', 'Payment')], default='Loan', max_length=20)),
                ('archived_data', models.JSONField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_type', models.CharField(max_length=50)),
                ('archived_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('control_number', models.CharField(max_length=50)),
                ('loan_type', models.CharField(max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('or_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('archived_loan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_history',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.08'), max_digits=5, verbose_name='Interest Rate')),
                ('service_fee_rate_emergency', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=5, verbose_name='Emergency Loan Service Fee Rate')),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=Decimal('0.02'), max_digits=5, verbose_name='Penalty Rate')),
                ('service_fee_rate_regular_1yr', models.DecimalField(decimal_places=3, default=Decimal('0.010'), max_digits=5, verbose_name='Regular Loan Service Fee Rate (<=1 year)')),
                ('service_fee_rate_regular_2yr', models.DecimalField(decimal_places=3, default=Decimal('0.015'), max_digits=5, verbose_name='Regular Loan Service Fee Rate (<=2 years)')),
                ('service_fee_rate_regular_3yr', models.DecimalField(decimal_places=3, default=Decimal('0.020'), max_digits=5, verbose_name='Regular Loan Service Fee Rate (<=3 years)')),
                ('service_fee_rate_regular_4yr', models.DecimalField(decimal_places=3, default=Decimal('0.025'), max_digits=5, verbose_name='Regular Loan Service Fee Rate (>3 years)')),
                ('admin_cost', models.DecimalField(decimal_places=2, default=Decimal('240.00'), max_digits=15)),
                ('notarial_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=200)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_type', models.CharField(max_length=50)),
                ('date_paid', models.DateTimeField()),
                ('or_number', models.CharField(blank=True, max_length=4, null=True)),
                ('payment_type', models.CharField(default='Schedule Payment', max_length=50)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archived_payment_records',
                'ordering': ['-date_paid'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='mcoop_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('control_number', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_type', models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency')], default='Emergency', max_length=200)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('loan_period', models.PositiveIntegerField(default=6)),
                ('loan_period_unit', models.CharField(choices=[('months', 'Months'), ('years', 'Years')], default='months', max_length=10)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Paid-off', 'Paid-off')], default='Ongoing', max_length=50)),
                ('takehomePay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('admincost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notarial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cisp', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('purpose', models.CharField(choices=[('Education', 'Education'), ('Medical/Emergency', 'Medical/Emergency'), ('House Construction', 'House Construction'), ('Commodity/Appliances', 'Commodity/Appliances'), ('Utility Services', 'Utility Services'), ('Others', 'Others')], default='Education', max_length=200)),
                ('annual_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('co_maker', models.CharField(blank=True, max_length=255)),
                ('co_maker_2', models.CharField(blank=True, max_length=255, null=True)),
                ('co_maker_3', models.CharField(blank=True, max_length=255, null=True)),
                ('co_maker_4', models.CharField(blank=True, max_length=255, null=True)),
                ('co_maker_5', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcoop_app.account')),
                ('system_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcoop_app.systemsettings')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('religion', models.CharField(default='Catholic', max_length=100)),
                ('pstatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('In a relationship', 'In a relationship'), ('Engaged', 'Engaged'), ('Baak', 'Baak')], default='Single', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, default='2616', max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('ann_com', models.CharField(blank=True, default='0', max_length=100)),
                ('mem_co', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(max_length=100)),
                ('addresss', models.CharField(default='Unknown', max_length=255)),
                ('birth_date1', models.DateField(blank=True, null=True)),
                ('beneficiary2', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship2', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date2', models.DateField(blank=True, null=True)),
                ('beneficiary3', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship3', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date3', models.DateField(blank=True, null=True)),
                ('tin', models.CharField(blank=True, max_length=100)),
                ('in_dep', models.CharField(max_length=100)),
                ('valid_id', models.CharField(choices=[('Philippine Passport', 'Philippine Passport'), ('Drivers License', 'Drivers License'), ('SSS ID', 'SSS ID'), ('GSIS ID', 'GSIS ID'), ('TIN ID', 'TIN ID'), ('Postal ID', 'Postal ID'), ('Voters ID', 'Voters ID'), ('PhilHealth ID', 'PhilHealth ID'), ('National ID', 'National ID')], default='TIN ID', max_length=50)),
                ('id_no', models.CharField(blank=True, default='Not Provided', max_length=100)),
                ('account_number', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='mcoop_app.account')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountN', to='mcoop_app.member'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('advance_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('under_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('received_amnt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('due_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('or_number', models.CharField(blank=True, max_length=4, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('loan_type', models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency')], default='Regular', max_length=20)),
                ('original_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcoop_app.loan')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('OR', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('loan', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='mcoop_app.loan')),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mcoop_app.paymentschedule')),
            ],
        ),
        migrations.CreateModel(
            name='LoanYearlyRecalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('previous_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('admincost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cisp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recalculated_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_recalculations', to='mcoop_app.loan')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('loan', 'year')},
            },
        ),
        migrations.AddConstraint(
            model_name='paymentschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('or_number__isnull', False), ('is_paid', True)), fields=('or_number', 'loan', 'loan_type'), name='unique_or_per_member_loan_type_paid'),
        ),
    ]
