# Generated by Django 5.1.3 on 2025-10-22 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORNumberTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('or_number', models.CharField(max_length=4)),
                ('loan_type', models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency')], max_length=20)),
                ('first_used_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='or_trackers', to='mcoop_app.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='or_numbers', to='mcoop_app.member')),
            ],
            options={
                'db_table': 'or_number_tracker',
                'ordering': ['-first_used_date'],
                'unique_together': {('member', 'or_number')},
            },
        ),
    ]
