# Generated by Django 5.1.3 on 2025-10-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0002_ornumbertracker'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentschedule',
            name='unique_or_per_member_loan_type_paid',
        ),
    ]
