# Generated by Django 5.1.3 on 2025-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0003_remove_paymentschedule_unique_or_per_member_loan_type_paid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['loan', 'is_paid', 'or_number'], name='mcoop_app_p_loan_id_daeabc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['loan', 'due_date'], name='mcoop_app_p_loan_id_5b4670_idx'),
        ),
    ]
