# Generated by Django 5.1.3 on 2025-11-27 16:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0004_paymentschedule_mcoop_app_p_loan_id_daeabc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('collection_method', models.CharField(choices=[('auto_borrower', 'Auto - Borrower Share Capital'), ('auto_comaker', 'Auto - Comaker Share Capital'), ('manual', 'Manual Payment')], max_length=50)),
                ('collected_from_account', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'penalty_collections',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='YearlyFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, unique=True)),
                ('total_loans_released', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_regular_loans', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_emergency_loans', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('loan_count', models.IntegerField(default=0)),
                ('total_penalties_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_service_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_admin_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_notarial_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_cisp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_fees_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('active_members', models.IntegerField(default=0)),
                ('new_members_added', models.IntegerField(default=0)),
                ('archived_members', models.IntegerField(default=0)),
                ('active_borrowers', models.IntegerField(default=0)),
                ('paid_off_borrowers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Yearly Financial Summary',
                'verbose_name_plural': 'Yearly Financial Summaries',
                'db_table': 'yearly_financial_summary',
                'ordering': ['-year'],
            },
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='takehomePay',
            new_name='net_proceeds',
        ),
        migrations.RemoveField(
            model_name='loanyearlyrecalculation',
            name='outstanding_balance',
        ),
        migrations.AddField(
            model_name='loan',
            name='is_reloan',
            field=models.BooleanField(default=False, help_text='Whether this loan is a reloan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='parent_loan',
            field=models.ForeignKey(blank=True, help_text='Original loan that this reloan is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_reloans', to='mcoop_app.loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed principal per payment = loan_amount / total_payments', max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='reloan_carried_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining balance carried over from parent loan', max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='reloan_date',
            field=models.DateField(blank=True, help_text='Date when reloan was processed', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining principal balance (Previous Balance for next year)', max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_payments',
            field=models.PositiveIntegerField(default=0, help_text='Total number of bi-monthly payments'),
        ),
        migrations.AddField(
            model_name='loanyearlyrecalculation',
            name='fees_or_number',
            field=models.CharField(blank=True, help_text='OR number for the yearly fees payment', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='loanyearlyrecalculation',
            name='fees_paid',
            field=models.BooleanField(default=False, help_text='Whether the yearly recalculation fees have been paid'),
        ),
        migrations.AddField(
            model_name='loanyearlyrecalculation',
            name='fees_paid_date',
            field=models.DateField(blank=True, help_text='Date when the yearly fees payment was made', null=True),
        ),
        migrations.AddField(
            model_name='loanyearlyrecalculation',
            name='new_bimonthly_amortization',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed Principal + (Year Interest / 24)', max_digits=15),
        ),
        migrations.AddField(
            model_name='loanyearlyrecalculation',
            name='notarial',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='loanyearlyrecalculation',
            name='total_fees_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total recalculated fees to be paid separately (Service + Admin + Notarial + CISP)', max_digits=15),
        ),
        migrations.AddField(
            model_name='member',
            name='employment_status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Outsider', 'Outsider')], default='Outsider', help_text="Member type: 'Employed' (salary deduction) or 'Outsider' (penalties applicable)", max_length=20),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='date_paid',
            field=models.DateField(blank=True, help_text='Actual date when this payment was made', null=True),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='interest_portion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest portion of this payment', max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='penalty_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='year_number',
            field=models.PositiveIntegerField(default=1, help_text='Which year this payment belongs to (1-4)'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Settled', 'Settled')], default='Ongoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanyearlyrecalculation',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, help_text='Interest for this year (distributed to 24 payments)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanyearlyrecalculation',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining principal at start of this year', max_digits=15),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='Interest Rate (in %)'),
        ),
        migrations.AddIndex(
            model_name='loanyearlyrecalculation',
            index=models.Index(fields=['loan', 'year'], name='mcoop_app_l_loan_id_cf607c_idx'),
        ),
        migrations.AddIndex(
            model_name='loanyearlyrecalculation',
            index=models.Index(fields=['loan', 'fees_paid'], name='mcoop_app_l_loan_id_4a341b_idx'),
        ),
        migrations.AddField(
            model_name='penaltycollection',
            name='payment_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_collections', to='mcoop_app.paymentschedule'),
        ),
        migrations.AddIndex(
            model_name='penaltycollection',
            index=models.Index(fields=['collection_date'], name='penalty_col_collect_53b84e_idx'),
        ),
        migrations.AddIndex(
            model_name='penaltycollection',
            index=models.Index(fields=['payment_schedule', 'collection_date'], name='penalty_col_payment_e055c2_idx'),
        ),
    ]
