# Generated by Django 5.1.3 on 2025-11-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0005_penaltycollection_yearlyfinancialsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='board_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='or_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
