# Generated by Django 5.1.3 on 2025-11-28 19:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0006_ledger_board_resolution_ledger_or_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='curtailed_principal_delta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of principal removed from this schedule due to a curtailment redistribution', max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='is_covered_by_advance',
            field=models.BooleanField(default=False, help_text='Marked True if this schedule was paid ahead by an advance coverage event'),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('regular', 'Regular'), ('pay_ahead', 'Pay Ahead'), ('curtail', 'Curtailment'), ('hybrid', 'Hybrid')], max_length=12)),
                ('curtailment_method', models.CharField(blank=True, choices=[('shorten', 'Shorten'), ('redistribute', 'Redistribute')], max_length=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, help_text='Primary schedule due date (for listing compatibility)', null=True)),
                ('or_number', models.CharField(blank=True, max_length=4, null=True)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_regular', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_pay_ahead', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_curtailment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('covered_schedule_ids', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True, help_text='Compatibility marker; events represent completed payments')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='mcoop_app.loan')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='mcoop_app.paymentschedule')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='advance_event',
            field=models.ForeignKey(blank=True, help_text='Reference to PaymentEvent that covered this schedule via pay-ahead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_schedules', to='mcoop_app.paymentevent'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['loan', 'is_paid', 'or_number'], name='mcoop_app_p_loan_id_ed8a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['loan', 'due_date'], name='mcoop_app_p_loan_id_dc050b_idx'),
        ),
    ]
