# Generated by Django 5.1.3 on 2025-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0007_paymentschedule_curtailed_principal_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='or_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
