# Generated by Django 5.1.6 on 2025-12-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0008_account_or_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedpayment',
            name='loan_control_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
