# Generated by Django 5.1.3 on 2025-12-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0009_archivedpayment_loan_control_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ornumbertracker',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='or_trackers', to='mcoop_app.loan'),
        ),
        migrations.AlterField(
            model_name='ornumbertracker',
            name='loan_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency'), ('Withdrawal', 'Withdrawal'), ('Advance', 'Advance'), ('Fees', 'Fees')], default='Regular', max_length=20),
        ),
    ]
